// Golden copies of the foliage and water plugins' injected code at HEAD 96b1149 (wave 10r polish), taken by W11-S
// before the SRO_CLOTH_WIND slot and the water ripple / profile slots (docs/WAVE_PLAN7.md §4.3). town-seams.test.ts
// asserts that the code with those off equals these byte for byte. Never edit.

export const HEAD_FOLIAGE_FRAGMENT_GLSL_W10R: Readonly<Record<string, string>> = {
  CUSTOM_FRAGMENT_DEFINITIONS: '#ifdef SRO_FOL_TRANSL\nfloat sroFolSh = -1.0;\n#endif\n',
  '!(diffuseBase\\+=info\\.diffuse\\*shadow;)': '$1\n#ifdef SRO_FOL_TRANSL\nif (sroFolSh < 0.0) {\n  sroFolSh = shadow;\n}\n#endif\n',
  CUSTOM_FRAGMENT_BEFORE_FINALCOLORCOMPOSITION: '#ifdef SRO_FOL_TRANSL\n#if defined(LIGHT0) && defined(DIRLIGHT0)\n{\n  vec3 folL = normalize(-light0.vLightData.xyz);\n  float folBack = pow(clamp(dot(viewDirectionW, -folL), 0.0, 1.0), 4.0);\n  float folThick = 0.5 + 0.5 * clamp(surfaceAlbedo.g * 4.0, 0.0, 1.0);\n  float folSh = sroFolSh < 0.0 ? 1.0 : sroFolSh;\n  finalDiffuse += light0.vLightDiffuse.rgb * surfaceAlbedo * (sroFol.x * folBack * folThick * folSh * 0.31830989);\n}\n#endif\n#endif\n',
}

export const HEAD_FOLIAGE_FRAGMENT_WGSL_W10R: Readonly<Record<string, string>> = {
  CUSTOM_FRAGMENT_DEFINITIONS: '#ifdef SRO_FOL_TRANSL\nvar<private> sroFolSh: f32 = -1.0;\n#endif\n',
  '!(diffuseBase\\+=info\\.diffuse\\*shadow;)': '$1\n#ifdef SRO_FOL_TRANSL\nif (sroFolSh < 0.0) {\n  sroFolSh = shadow;\n}\n#endif\n',
  CUSTOM_FRAGMENT_BEFORE_FINALCOLORCOMPOSITION: '#ifdef SRO_FOL_TRANSL\n#if defined(LIGHT0) && defined(DIRLIGHT0)\n{\n  let folL = normalize(-light0.vLightData.xyz);\n  let folBack = pow(clamp(dot(viewDirectionW, -folL), 0.0, 1.0), 4.0);\n  let folThick = 0.5 + 0.5 * clamp(surfaceAlbedo.g * 4.0, 0.0, 1.0);\n  let folSh = select(sroFolSh, 1.0, sroFolSh < 0.0);\n  finalDiffuse = finalDiffuse + light0.vLightDiffuse.rgb * surfaceAlbedo * (uniforms.sroFol.x * folBack * folThick * folSh * 0.31830989);\n}\n#endif\n#endif\n',
}

export const HEAD_FOLIAGE_VERTEX_GLSL_W10R: Readonly<Record<string, string>> = {
  CUSTOM_VERTEX_DEFINITIONS: '#if defined(SRO_FOL_WIND) || defined(SRO_FOL_FLUTTER)\nvec3 sroWind(vec3 root) {\n  float t = wxB.w;\n  float z = clamp(wxB.z, 0.0, 1.0);\n  float ph = dot(root.xz, vec2(0.21, 0.17));\n  float sway = sin(t * 1.9 + ph) * 0.65 + sin(t * 3.3 + ph * 1.7) * 0.35;\n  float gust = sin(dot(root.xz, wxB.xy) * 0.35 - t * 2.1);\n  return vec3(sway + 0.5 * z * gust + 0.6 * z, 0.4 + 2.2 * z, clamp(wxA.z, 0.0, 1.0));\n}\n#endif\n#ifdef SRO_FOL_PIVOT\nattribute vec3 sroPivot;\n#endif\n',
  CUSTOM_VERTEX_UPDATE_WORLDPOS: '#if defined(SRO_FOL_WIND) || defined(SRO_FOL_FLUTTER)\n{\n#ifdef SRO_FOL_PIVOT\n  vec3 folRoot = (finalWorld * vec4(sroPivot, 1.0)).xyz;\n#else\n  vec3 folRoot = finalWorld[3].xyz;\n#endif\n  float folH = clamp(worldPos.y - folRoot.y, 0.0, 12.0);\n#ifdef SRO_FOL_BREEZE\n  float folZ = max(clamp(wxB.z, 0.0, 1.0), sroFol.y);\n#else\n  float folZ = clamp(wxB.z, 0.0, 1.0);\n#endif\n  vec3 folO = vec3(0.0);\n#ifdef SRO_FOL_WIND\n  vec3 folWd = sroWind(folRoot);\n  float folB = folZ * folH * folH * 0.012 * folWd.x;\n  folO = vec3(wxB.x * folB, 0.0, wxB.y * folB);\n#endif\n#ifdef SRO_FOL_FLUTTER\n  float folF = sin(wxB.w * 7.3 + dot(worldPos.xyz, vec3(1.7, 2.3, 1.1))) * (0.012 + 0.05 * folZ) * clamp(folH / 3.0, 0.0, 1.0);\n  folO += vec3(wxB.x * folF, 0.5 * folF, wxB.y * folF);\n#endif\n  worldPos.xyz += folO;\n  vPositionW = worldPos.xyz;\n}\n#endif\n',
}

export const HEAD_FOLIAGE_VERTEX_WGSL_W10R: Readonly<Record<string, string>> = {
  CUSTOM_VERTEX_DEFINITIONS: '#if defined(SRO_FOL_WIND) || defined(SRO_FOL_FLUTTER)\nfn sroWind(root: vec3f) -> vec3f {\n  let t = uniforms.wxB.w;\n  let z = clamp(uniforms.wxB.z, 0.0, 1.0);\n  let ph = dot(root.xz, vec2f(0.21, 0.17));\n  let sway = sin(t * 1.9 + ph) * 0.65 + sin(t * 3.3 + ph * 1.7) * 0.35;\n  let gust = sin(dot(root.xz, uniforms.wxB.xy) * 0.35 - t * 2.1);\n  return vec3f(sway + 0.5 * z * gust + 0.6 * z, 0.4 + 2.2 * z, clamp(uniforms.wxA.z, 0.0, 1.0));\n}\n#endif\n#ifdef SRO_FOL_PIVOT\nattribute sroPivot: vec3f;\n#endif\n',
  CUSTOM_VERTEX_UPDATE_WORLDPOS: '#if defined(SRO_FOL_WIND) || defined(SRO_FOL_FLUTTER)\n{\n#ifdef SRO_FOL_PIVOT\n  let folRoot = (finalWorld * vec4f(vertexInputs.sroPivot, 1.0)).xyz;\n#else\n  let folRoot = finalWorld[3].xyz;\n#endif\n  let folH = clamp(worldPos.y - folRoot.y, 0.0, 12.0);\n#ifdef SRO_FOL_BREEZE\n  let folZ = max(clamp(uniforms.wxB.z, 0.0, 1.0), uniforms.sroFol.y);\n#else\n  let folZ = clamp(uniforms.wxB.z, 0.0, 1.0);\n#endif\n  var folO = vec3f(0.0);\n#ifdef SRO_FOL_WIND\n  let folWd = sroWind(folRoot);\n  let folB = folZ * folH * folH * 0.012 * folWd.x;\n  folO = vec3f(uniforms.wxB.x * folB, 0.0, uniforms.wxB.y * folB);\n#endif\n#ifdef SRO_FOL_FLUTTER\n  let folF = sin(uniforms.wxB.w * 7.3 + dot(worldPos.xyz, vec3f(1.7, 2.3, 1.1))) * (0.012 + 0.05 * folZ) * clamp(folH / 3.0, 0.0, 1.0);\n  folO = folO + vec3f(uniforms.wxB.x * folF, 0.5 * folF, uniforms.wxB.y * folF);\n#endif\n  worldPos = vec4f(worldPos.xyz + folO, worldPos.w);\n  vertexOutputs.vPositionW = worldPos.xyz;\n}\n#endif\n',
}

export const HEAD_WATER_FRAGMENT_GLSL_W10R: Readonly<Record<string, string>> = {
  CUSTOM_FRAGMENT_DEFINITIONS: '#ifdef SRO_WATER\nuniform highp sampler2DArray sroWaterFrames;\nuniform sampler2D sroWaterNormal;\n#ifdef SRO_WATER_RIPPLE\nuniform sampler2D sroWaterRipple;\nvec3 sroWRing(vec4 r, float off) {\n  float ph = fract(r.a + sroWaterA.w * 1.1 + off);\n  float ring = (r.r * 2.0 - 1.0 + ph - 1.0) * 20.0;\n  float s = clamp(sin(clamp(ring, 0.0, 9.42)) * (1.0 - ph), 0.0, 1.0);\n  return vec3((r.gb * 2.0 - vec2(1.0)) * s, s);\n}\n#endif\nvec3 sroWAlb;\nfloat sroWAlpha;\nvec3 sroWN;\n#endif\n',
  CUSTOM_FRAGMENT_MAIN_BEGIN: '#ifdef SRO_WATER\n{\n  vec2 sroWP = vPositionW.xz;\n  float sroWT = sroWaterA.y;\n  vec3 sroWF = texture(sroWaterFrames, vec3(sroWP / 8.0, floor(sroWaterA.x + 0.5))).rgb;\n  float sroWD = vColor.r * 9.0 - 1.0;\n  float sroWAmp = vColor.g * 2.0 * sroWaterC.w;\n  vec2 sroN0 = texture(sroWaterNormal, (sroWP + sroWT * vec2(0.030, 0.010)) / 6.0).xy * 2.0 - vec2(1.0);\n  vec2 sroN1 = texture(sroWaterNormal, (sroWP + sroWT * vec2(-0.020, 0.025)) / 17.0).xy * 2.0 - vec2(1.0);\n  vec2 sroSlope = (sroN0 + sroN1 * 0.7) * (0.35 * sroWAmp);\n#ifdef SRO_WATER_RIPPLE\n  vec2 sroRu = sroWP * 0.5;\n  vec3 sroR = sroWRing(texture(sroWaterRipple, sroRu), 0.0) + sroWRing(texture(sroWaterRipple, sroRu * 1.37 + vec2(0.43, 0.71)), 0.5);\n  sroSlope += sroR.xy * (0.5 * sroWaterA.z);\n#endif\n  sroWN = normalize(vec3(sroSlope.x, 1.0, -sroSlope.y));\n  vec3 sroShallow = pow(clamp(sroWF * sroWaterB.rgb, 0.0, 1.0), vec3(2.2)) * 0.60;\n#ifdef SRO_WATER_SHORE\n  float sroDeep = clamp(sroWD / 4.0, 0.0, 1.0);\n  float sroFoam = (1.0 - smoothstep(0.05, 0.30, sroWD)) * smoothstep(-0.05, 0.02, sroWD) * clamp(0.6 + sroN0.x, 0.0, 1.0);\n  sroWAlpha = max(clamp(sroWD / 1.50, 0.0, 1.0), sroFoam * 0.7);\n  sroWAlb = mix(mix(sroShallow, sroShallow * sroWaterC.rgb, sroDeep), vec3(0.55), sroFoam);\n#else\n  float sroDeep = clamp(vColor.a, 0.0, 1.0);\n  sroWAlpha = clamp(vColor.a, 0.0, 1.0);\n  sroWAlb = mix(sroShallow, sroShallow * sroWaterC.rgb, sroDeep);\n#endif\n}\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_ALBEDO: '#ifdef SRO_WATER\nsurfaceAlbedo = sroWAlb;\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_ALPHA: '#ifdef SRO_WATER\nalpha = sroWAlpha;\nnormalW = sroWN;\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_METALLICROUGHNESS: '#ifdef SRO_WATER\nmetallicRoughness = vec2(0.0, sroWaterB.w);\n#endif\n',
}

export const HEAD_WATER_FRAGMENT_WGSL_W10R: Readonly<Record<string, string>> = {
  CUSTOM_FRAGMENT_DEFINITIONS: '#ifdef SRO_WATER\nvar sroWaterFrames: texture_2d_array<f32>;\nvar sroWaterFramesSampler: sampler;\nvar sroWaterNormal: texture_2d<f32>;\nvar sroWaterNormalSampler: sampler;\n#ifdef SRO_WATER_RIPPLE\nvar sroWaterRipple: texture_2d<f32>;\nvar sroWaterRippleSampler: sampler;\nfn sroWRing(r: vec4f, off: f32) -> vec3f {\n  let ph = fract(r.a + uniforms.sroWaterA.w * 1.1 + off);\n  let ring = (r.r * 2.0 - 1.0 + ph - 1.0) * 20.0;\n  let s = clamp(sin(clamp(ring, 0.0, 9.42)) * (1.0 - ph), 0.0, 1.0);\n  return vec3f((r.gb * 2.0 - vec2f(1.0)) * s, s);\n}\n#endif\nvar<private> sroWAlb: vec3f;\nvar<private> sroWAlpha: f32;\nvar<private> sroWN: vec3f;\n#endif\n',
  CUSTOM_FRAGMENT_MAIN_BEGIN: '#ifdef SRO_WATER\n{\n  let sroWP = fragmentInputs.vPositionW.xz;\n  let sroWT = uniforms.sroWaterA.y;\n  let sroWF = textureSample(sroWaterFrames, sroWaterFramesSampler, sroWP / 8.0, i32(uniforms.sroWaterA.x + 0.5)).rgb;\n  let sroWD = fragmentInputs.vColor.r * 9.0 - 1.0;\n  let sroWAmp = fragmentInputs.vColor.g * 2.0 * uniforms.sroWaterC.w;\n  let sroN0 = textureSample(sroWaterNormal, sroWaterNormalSampler, (sroWP + sroWT * vec2f(0.030, 0.010)) / 6.0).xy * 2.0 - vec2f(1.0);\n  let sroN1 = textureSample(sroWaterNormal, sroWaterNormalSampler, (sroWP + sroWT * vec2f(-0.020, 0.025)) / 17.0).xy * 2.0 - vec2f(1.0);\n  var sroSlope = (sroN0 + sroN1 * 0.7) * (0.35 * sroWAmp);\n#ifdef SRO_WATER_RIPPLE\n  let sroRu = sroWP * 0.5;\n  let sroR = sroWRing(textureSample(sroWaterRipple, sroWaterRippleSampler, sroRu), 0.0) + sroWRing(textureSample(sroWaterRipple, sroWaterRippleSampler, sroRu * 1.37 + vec2f(0.43, 0.71)), 0.5);\n  sroSlope = sroSlope + sroR.xy * (0.5 * uniforms.sroWaterA.z);\n#endif\n  sroWN = normalize(vec3f(sroSlope.x, 1.0, -sroSlope.y));\n  let sroShallow = pow(clamp(sroWF * uniforms.sroWaterB.rgb, vec3f(0.0), vec3f(1.0)), vec3f(2.2)) * 0.60;\n#ifdef SRO_WATER_SHORE\n  let sroDeep = clamp(sroWD / 4.0, 0.0, 1.0);\n  let sroFoam = (1.0 - smoothstep(0.05, 0.30, sroWD)) * smoothstep(-0.05, 0.02, sroWD) * clamp(0.6 + sroN0.x, 0.0, 1.0);\n  sroWAlpha = max(clamp(sroWD / 1.50, 0.0, 1.0), sroFoam * 0.7);\n  sroWAlb = mix(mix(sroShallow, sroShallow * uniforms.sroWaterC.rgb, sroDeep), vec3f(0.55), sroFoam);\n#else\n  let sroDeep = clamp(fragmentInputs.vColor.a, 0.0, 1.0);\n  sroWAlpha = clamp(fragmentInputs.vColor.a, 0.0, 1.0);\n  sroWAlb = mix(sroShallow, sroShallow * uniforms.sroWaterC.rgb, sroDeep);\n#endif\n}\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_ALBEDO: '#ifdef SRO_WATER\nsurfaceAlbedo = sroWAlb;\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_ALPHA: '#ifdef SRO_WATER\nalpha = sroWAlpha;\nnormalW = sroWN;\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_METALLICROUGHNESS: '#ifdef SRO_WATER\nmetallicRoughness = vec2f(0.0, uniforms.sroWaterB.w);\n#endif\n',
}
