// Golden copies of the object plugins' injected code at HEAD 180f11c (packages/world-render/src/pbr/surface-plugin.ts
// `surfaceFragmentCode`, pbr/foliage-plugin.ts `foliageCode`), taken before BT-P's SRO_TABLE, SRO_FOL_PIVOT and
// SRO_FOL_BREEZE (docs/BATCHING.md §3.4, §3.5). pbr-table.test.ts asserts that the code with those defines off equals
// these byte for byte (batching off = HEAD). Never edit; regenerate only if the frozen wave-9 chunks it embeds change.

export const HEAD_SURFACE_WGSL: Readonly<Record<string, string>> = {
  CUSTOM_FRAGMENT_DEFINITIONS: '#ifdef SRO_SURFACE\n#ifdef SRO_SHELTER\nvar wxOccMap: texture_2d<f32>;\nvar wxOccMapSampler: sampler;\nfn wxOccUv(xz: vec2f) -> vec2f {\n  let d = xz - uniforms.wxOcc.xy;\n  return vec2f(dot(uniforms.wxOccM.xy, d), dot(uniforms.wxOccM.zw, d)) * 0.5 + vec2f(0.5);\n}\nfn sroShelterTop(xz: vec2f) -> f32 {\n  let uv = wxOccUv(xz);\n  let t = textureSampleLevel(wxOccMap, wxOccMapSampler, uv, 0.0);\n#ifdef WX_OCC8\n  let rel = (t.r * 65280.0 + t.g * 255.0) / 65535.0 * 128.0 - 64.0;\n#else\n  let rel = t.r;\n#endif\n  let inside = uv.x > 0.0 && uv.x < 1.0 && uv.y > 0.0 && uv.y < 1.0 && uniforms.wxCam.w > 0.5;\n  return select(-10000.0, rel + uniforms.wxF.x, inside);\n}\nfn sroShelter(p: vec3f) -> f32 {\n  let uv = wxOccUv(p.xz);\n  let edge = min(min(uv.x, uv.y), min(1.0 - uv.x, 1.0 - uv.y)) * uniforms.wxOcc.z;\n  let s = 1.0 - smoothstep(0.25, 1.0, sroShelterTop(p.xz) - p.y);\n  return mix(1.0, s, smoothstep(0.0, 4.0, edge));\n}\n\n#endif\n#ifdef SRO_CLOUDSHADOW\nvar cloudNoise: texture_2d<f32>;\nvar cloudNoiseSampler: sampler;\nfn sroCloudShadow(p: vec3f) -> f32 {\n  let s = uniforms.skyCloudShadow;\n  let q = uniforms.skyCloudProj;\n  let uv = (p.xz + q.xy * (q.z - p.y)) * s.z + s.xy;\n  let low = textureSampleLevel(cloudNoise, cloudNoiseSampler, uv * 0.25, 0.0).a;\n  let cov = clamp(q.w + (low - 0.5) * 0.3 * (1.0 - q.w), 0.001, 1.0);\n  let r = textureSampleLevel(cloudNoise, cloudNoiseSampler, uv, 1.0).r;\n  let d = clamp((r - (1.0 - cov)) / cov, 0.0, 1.0);\n  return 1.0 - s.w * (1.0 - exp(-d * 9.0));\n}\n\n#endif\nvar<private> sroLuma: f32;\nvar<private> sroLumaK: f32;\nvar<private> sroWetW: f32;\nvar<private> sroWetRough: f32;\nvar<private> sroPuddle: f32;\nvar<private> sroDark: f32;\nfn sroHash(p: vec2f) -> f32 {\n  var p3 = fract(vec3f(p.x, p.y, p.x) * 0.1031);\n  p3 = p3 + dot(p3, p3.yzx + vec3f(33.33));\n  return fract((p3.x + p3.y) * p3.z);\n}\nfn sroNoise(p: vec2f) -> f32 {\n  let i = floor(p);\n  let f = fract(p);\n  let u = f * f * (vec2f(3.0) - 2.0 * f);\n  return mix(mix(sroHash(i), sroHash(i + vec2f(1.0, 0.0)), u.x), mix(sroHash(i + vec2f(0.0, 1.0)), sroHash(i + vec2f(1.0, 1.0)), u.x), u.y);\n}\nfn sroRoughness(r: f32) -> f32 {\n  var o = r;\n#ifdef SRO_LUMA_ROUGH\n  o = clamp(o + sroLumaK * (0.5 - sroLuma), 0.02, 1.0);\n#endif\n#ifdef SRO_WET\n  o = mix(o, sroWetRough, sroWetW);\n  o = mix(o, 0.03, sroPuddle);\n#endif\n  return o;\n}\n#endif\n',
  CUSTOM_FRAGMENT_MAIN_BEGIN: '#ifdef SRO_SURFACE\n{\n  sroLumaK = uniforms.sroSurf.x;\n  sroWetRough = uniforms.sroSurf.z;\n  sroWetW = 0.0;\n  sroPuddle = 0.0;\n  sroDark = 1.0;\n#ifdef SRO_WET\n  var sroN = vec3f(0.0, 1.0, 0.0);\n#ifdef NORMAL\n  sroN = normalize(fragmentInputs.vNormalW);\n#endif\n  var sroShel = 1.0;\n#ifdef SRO_SHELTER\n  sroShel = sroShelter(fragmentInputs.vPositionW);\n#endif\n  let sroExpo = smoothstep(-0.5, -0.2, sroN.y) * mix(0.6, 1.0, smoothstep(0.0, 0.6, sroN.y));\n  sroWetW = clamp(uniforms.sroWeather.y * sroExpo * sroShel, 0.0, 1.0);\n#ifdef SRO_PUDDLES\n  let sroFlat = smoothstep(0.95, 0.99, sroN.y);\n  let sroP = 1.0 - uniforms.sroWeather.z * 0.45;\n  let sroMask = 0.35 + sroNoise(fragmentInputs.vPositionW.xz * 0.15) * 0.3;\n  sroPuddle = smoothstep(sroP - 0.05, sroP + 0.05, sroMask) * sroFlat * uniforms.sroSurf.w * sroShel;\n#endif\n  sroDark = mix(1.0, 1.0 - 0.5 * uniforms.sroSurf.y, sroWetW) * mix(1.0, 0.6, sroPuddle);\n#endif\n}\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_ALBEDO: '#ifdef SRO_SURFACE\nsroLuma = dot(surfaceAlbedo, vec3f(0.2126, 0.7152, 0.0722));\n#ifdef SRO_WET\nsurfaceAlbedo = surfaceAlbedo * sroDark;\n#endif\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_METALLICROUGHNESS: '#ifdef SRO_SURFACE\nmetallicRoughness = vec2f(metallicRoughness.x, sroRoughness(metallicRoughness.y));\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_ALPHA: '#ifdef SRO_SURFACE\n#ifdef SRO_WET\nnormalW = normalize(mix(normalW, geometricNormalW, 0.5 * sroWetW));\n#ifdef SRO_PUDDLES\nnormalW = normalize(mix(normalW, vec3f(0.0, 1.0, 0.0), sroPuddle));\n#endif\n#endif\n#endif\n',
  CUSTOM_LIGHT0_COLOR: '#ifdef SRO_SURFACE\n#if defined(SRO_BAKED) || defined(SRO_CLOUDSHADOW)\n{\n  var sroVis = 1.0;\n#ifdef SRO_BAKED\n  let sroLm = dot(lightmapColor.rgb, vec3f(0.2126, 0.7152, 0.0722));\n  let sroBaked = mix(1.0, clamp((sroLm - uniforms.sroBake.x) * uniforms.sroBake.y, 0.0, 1.0), uniforms.sroSun.x);\n  let sroDist = distance(fragmentInputs.vPositionW, scene.vEyePosition.xyz);\n  let sroCsm = uniforms.sroSun.w * (1.0 - clamp((sroDist - uniforms.sroSun.y) * uniforms.sroSun.z, 0.0, 1.0));\n  sroVis = mix(sroBaked, 1.0, sroCsm);\n#endif\n#ifdef SRO_CLOUDSHADOW\n  sroVis = sroVis * sroCloudShadow(fragmentInputs.vPositionW);\n#endif\n  diffuse0 = vec4f(diffuse0.rgb * sroVis, diffuse0.a);\n}\n#endif\n#endif\n',
  CUSTOM_FRAGMENT_BEFORE_FINALCOLORCOMPOSITION: '#ifdef SRO_SURFACE\n#ifdef SRO_SELFLIT\nfinalEmissive = finalEmissive * surfaceAlbedo;\n#endif\n#ifdef SRO_BAKED\n{\n  let sroLmA = dot(lightmapColor.rgb, vec3f(0.2126, 0.7152, 0.0722));\n  let sroAO = mix(1.0, clamp(sroLmA * uniforms.sroBake.z, 0.0, 1.0), uniforms.sroBake.w);\n#if !defined(UNLIT) && defined(REFLECTION)\n  finalIrradiance = finalIrradiance * sroAO;\n#endif\n  finalAmbient = finalAmbient * sroAO;\n}\n#endif\n#if defined(SRO_WET) && defined(REFLECTION) && !defined(UNLIT)\n{\n  let sroIn = dot((finalIrradiance + finalDiffuse) / max(surfaceAlbedo, vec3f(0.02)), vec3f(0.2126, 0.7152, 0.0722));\n  let sroRefl = dot(finalRadianceScaled, vec3f(0.2126, 0.7152, 0.0722));\n  let sroK = min(1.0, sroIn * 0.60 / max(sroRefl, 1e-6));\n  finalRadianceScaled = finalRadianceScaled * mix(1.0, sroK, clamp(max(sroWetW, sroPuddle), 0.0, 1.0));\n}\n#endif\n#ifdef SRO_LAMP\nfinalEmissive = finalEmissive + surfaceAlbedo * (uniforms.sroMisc.x * uniforms.sroMisc.z);\n#endif\n#endif\n',
  CUSTOM_FRAGMENT_BEFORE_FRAGCOLOR: '#ifdef SRO_SURFACE\n#if defined(PREPASS_REFLECTIVITY) && !defined(UNLIT)\n{\n  let sroFlatN = smoothstep(0.9, 0.98, geometricNormalW.y);\n  let sroM = clamp(max(uniforms.sroMisc.y, max(sroPuddle, sroWetW * sroFlatN)), 0.0, 1.0);\n  specularEnvironmentR0 = max(specularEnvironmentR0, vec3f(0.02 + 0.18 * sroM));\n  microSurface = max(microSurface, mix(microSurface, 0.95, sroM));\n}\n#endif\n#endif\n',
}

export const HEAD_SURFACE_GLSL: Readonly<Record<string, string>> = {
  CUSTOM_FRAGMENT_DEFINITIONS: '#ifdef SRO_SURFACE\n#ifdef SRO_SHELTER\nuniform highp sampler2D wxOccMap;\nvec2 wxOccUv(vec2 xz) {\n  vec2 d = xz - wxOcc.xy;\n  return vec2(dot(wxOccM.xy, d), dot(wxOccM.zw, d)) * 0.5 + vec2(0.5);\n}\nfloat sroShelterTop(vec2 xz) {\n  vec2 uv = wxOccUv(xz);\n  vec4 t = textureLod(wxOccMap, uv, 0.0);\n#ifdef WX_OCC8\n  float rel = (t.r * 65280.0 + t.g * 255.0) / 65535.0 * 128.0 - 64.0;\n#else\n  float rel = t.r;\n#endif\n  bool inside = uv.x > 0.0 && uv.x < 1.0 && uv.y > 0.0 && uv.y < 1.0 && wxCam.w > 0.5;\n  return inside ? rel + wxF.x : -10000.0;\n}\nfloat sroShelter(vec3 p) {\n  vec2 uv = wxOccUv(p.xz);\n  float edge = min(min(uv.x, uv.y), min(1.0 - uv.x, 1.0 - uv.y)) * wxOcc.z;\n  float s = 1.0 - smoothstep(0.25, 1.0, sroShelterTop(p.xz) - p.y);\n  return mix(1.0, s, smoothstep(0.0, 4.0, edge));\n}\n\n#endif\n#ifdef SRO_CLOUDSHADOW\nuniform sampler2D cloudNoise;\nfloat sroCloudShadow(vec3 p) {\n  vec4 s = skyCloudShadow;\n  vec4 q = skyCloudProj;\n  vec2 uv = (p.xz + q.xy * (q.z - p.y)) * s.z + s.xy;\n  float low = textureLod(cloudNoise, uv * 0.25, 0.0).a;\n  float cov = clamp(q.w + (low - 0.5) * 0.3 * (1.0 - q.w), 0.001, 1.0);\n  float r = textureLod(cloudNoise, uv, 1.0).r;\n  float d = clamp((r - (1.0 - cov)) / cov, 0.0, 1.0);\n  return 1.0 - s.w * (1.0 - exp(-d * 9.0));\n}\n\n#endif\nfloat sroLuma;\nfloat sroLumaK;\nfloat sroWetW;\nfloat sroWetRough;\nfloat sroPuddle;\nfloat sroDark;\nfloat sroHash(vec2 p) {\n  vec3 p3 = fract(vec3(p.x, p.y, p.x) * 0.1031);\n  p3 += dot(p3, p3.yzx + vec3(33.33));\n  return fract((p3.x + p3.y) * p3.z);\n}\nfloat sroNoise(vec2 p) {\n  vec2 i = floor(p);\n  vec2 f = fract(p);\n  vec2 u = f * f * (vec2(3.0) - 2.0 * f);\n  return mix(mix(sroHash(i), sroHash(i + vec2(1.0, 0.0)), u.x), mix(sroHash(i + vec2(0.0, 1.0)), sroHash(i + vec2(1.0, 1.0)), u.x), u.y);\n}\nfloat sroRoughness(float r) {\n  float o = r;\n#ifdef SRO_LUMA_ROUGH\n  o = clamp(o + sroLumaK * (0.5 - sroLuma), 0.02, 1.0);\n#endif\n#ifdef SRO_WET\n  o = mix(o, sroWetRough, sroWetW);\n  o = mix(o, 0.03, sroPuddle);\n#endif\n  return o;\n}\n#endif\n',
  CUSTOM_FRAGMENT_MAIN_BEGIN: '#ifdef SRO_SURFACE\n{\n  sroLumaK = sroSurf.x;\n  sroWetRough = sroSurf.z;\n  sroWetW = 0.0;\n  sroPuddle = 0.0;\n  sroDark = 1.0;\n#ifdef SRO_WET\n  vec3 sroN = vec3(0.0, 1.0, 0.0);\n#ifdef NORMAL\n  sroN = normalize(vNormalW);\n#endif\n  float sroShel = 1.0;\n#ifdef SRO_SHELTER\n  sroShel = sroShelter(vPositionW);\n#endif\n  float sroExpo = smoothstep(-0.5, -0.2, sroN.y) * mix(0.6, 1.0, smoothstep(0.0, 0.6, sroN.y));\n  sroWetW = clamp(sroWeather.y * sroExpo * sroShel, 0.0, 1.0);\n#ifdef SRO_PUDDLES\n  float sroFlat = smoothstep(0.95, 0.99, sroN.y);\n  float sroP = 1.0 - sroWeather.z * 0.45;\n  float sroMask = 0.35 + sroNoise(vPositionW.xz * 0.15) * 0.3;\n  sroPuddle = smoothstep(sroP - 0.05, sroP + 0.05, sroMask) * sroFlat * sroSurf.w * sroShel;\n#endif\n  sroDark = mix(1.0, 1.0 - 0.5 * sroSurf.y, sroWetW) * mix(1.0, 0.6, sroPuddle);\n#endif\n}\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_ALBEDO: '#ifdef SRO_SURFACE\nsroLuma = dot(surfaceAlbedo, vec3(0.2126, 0.7152, 0.0722));\n#ifdef SRO_WET\nsurfaceAlbedo = surfaceAlbedo * sroDark;\n#endif\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_METALLICROUGHNESS: '#ifdef SRO_SURFACE\nmetallicRoughness = vec2(metallicRoughness.x, sroRoughness(metallicRoughness.y));\n#endif\n',
  CUSTOM_FRAGMENT_UPDATE_ALPHA: '#ifdef SRO_SURFACE\n#ifdef SRO_WET\nnormalW = normalize(mix(normalW, geometricNormalW, 0.5 * sroWetW));\n#ifdef SRO_PUDDLES\nnormalW = normalize(mix(normalW, vec3(0.0, 1.0, 0.0), sroPuddle));\n#endif\n#endif\n#endif\n',
  CUSTOM_LIGHT0_COLOR: '#ifdef SRO_SURFACE\n#if defined(SRO_BAKED) || defined(SRO_CLOUDSHADOW)\n{\n  float sroVis = 1.0;\n#ifdef SRO_BAKED\n  float sroLm = dot(lightmapColor.rgb, vec3(0.2126, 0.7152, 0.0722));\n  float sroBaked = mix(1.0, clamp((sroLm - sroBake.x) * sroBake.y, 0.0, 1.0), sroSun.x);\n  float sroDist = distance(vPositionW, vEyePosition.xyz);\n  float sroCsm = sroSun.w * (1.0 - clamp((sroDist - sroSun.y) * sroSun.z, 0.0, 1.0));\n  sroVis = mix(sroBaked, 1.0, sroCsm);\n#endif\n#ifdef SRO_CLOUDSHADOW\n  sroVis = sroVis * sroCloudShadow(vPositionW);\n#endif\n  diffuse0 = vec4(diffuse0.rgb * sroVis, diffuse0.a);\n}\n#endif\n#endif\n',
  CUSTOM_FRAGMENT_BEFORE_FINALCOLORCOMPOSITION: '#ifdef SRO_SURFACE\n#ifdef SRO_SELFLIT\nfinalEmissive = finalEmissive * surfaceAlbedo;\n#endif\n#ifdef SRO_BAKED\n{\n  float sroLmA = dot(lightmapColor.rgb, vec3(0.2126, 0.7152, 0.0722));\n  float sroAO = mix(1.0, clamp(sroLmA * sroBake.z, 0.0, 1.0), sroBake.w);\n#if !defined(UNLIT) && defined(REFLECTION)\n  finalIrradiance = finalIrradiance * sroAO;\n#endif\n  finalAmbient = finalAmbient * sroAO;\n}\n#endif\n#if defined(SRO_WET) && defined(REFLECTION) && !defined(UNLIT)\n{\n  float sroIn = dot((finalIrradiance + finalDiffuse) / max(surfaceAlbedo, vec3(0.02)), vec3(0.2126, 0.7152, 0.0722));\n  float sroRefl = dot(finalRadianceScaled, vec3(0.2126, 0.7152, 0.0722));\n  float sroK = min(1.0, sroIn * 0.60 / max(sroRefl, 1e-6));\n  finalRadianceScaled = finalRadianceScaled * mix(1.0, sroK, clamp(max(sroWetW, sroPuddle), 0.0, 1.0));\n}\n#endif\n#ifdef SRO_LAMP\nfinalEmissive = finalEmissive + surfaceAlbedo * (sroMisc.x * sroMisc.z);\n#endif\n#endif\n',
  CUSTOM_FRAGMENT_BEFORE_FRAGCOLOR: '#ifdef SRO_SURFACE\n#if defined(PREPASS_REFLECTIVITY) && !defined(UNLIT)\n{\n  float sroFlatN = smoothstep(0.9, 0.98, geometricNormalW.y);\n  float sroM = clamp(max(sroMisc.y, max(sroPuddle, sroWetW * sroFlatN)), 0.0, 1.0);\n  specularEnvironmentR0 = max(specularEnvironmentR0, vec3(0.02 + 0.18 * sroM));\n  microSurface = max(microSurface, mix(microSurface, 0.95, sroM));\n}\n#endif\n#endif\n',
}

export const HEAD_FOLIAGE_VERTEX_WGSL: Readonly<Record<string, string>> = {
  CUSTOM_VERTEX_DEFINITIONS: '#if defined(SRO_FOL_WIND) || defined(SRO_FOL_FLUTTER)\nfn sroWind(root: vec3f) -> vec3f {\n  let t = uniforms.wxB.w;\n  let z = clamp(uniforms.wxB.z, 0.0, 1.0);\n  let ph = dot(root.xz, vec2f(0.21, 0.17));\n  let sway = sin(t * 1.9 + ph) * 0.65 + sin(t * 3.3 + ph * 1.7) * 0.35;\n  let gust = sin(dot(root.xz, uniforms.wxB.xy) * 0.35 - t * 2.1);\n  return vec3f(sway + 0.5 * z * gust + 0.6 * z, 0.4 + 2.2 * z, clamp(uniforms.wxA.z, 0.0, 1.0));\n}\n#endif\n',
  CUSTOM_VERTEX_UPDATE_WORLDPOS: '#if defined(SRO_FOL_WIND) || defined(SRO_FOL_FLUTTER)\n{\n  let folRoot = finalWorld[3].xyz;\n  let folH = clamp(worldPos.y - folRoot.y, 0.0, 12.0);\n  let folZ = clamp(uniforms.wxB.z, 0.0, 1.0);\n  var folO = vec3f(0.0);\n#ifdef SRO_FOL_WIND\n  let folWd = sroWind(folRoot);\n  let folB = folZ * folH * folH * 0.012 * folWd.x;\n  folO = vec3f(uniforms.wxB.x * folB, 0.0, uniforms.wxB.y * folB);\n#endif\n#ifdef SRO_FOL_FLUTTER\n  let folF = sin(uniforms.wxB.w * 7.3 + dot(worldPos.xyz, vec3f(1.7, 2.3, 1.1))) * (0.012 + 0.05 * folZ) * clamp(folH / 3.0, 0.0, 1.0);\n  folO = folO + vec3f(uniforms.wxB.x * folF, 0.5 * folF, uniforms.wxB.y * folF);\n#endif\n  worldPos = vec4f(worldPos.xyz + folO, worldPos.w);\n  vertexOutputs.vPositionW = worldPos.xyz;\n}\n#endif\n',
}

export const HEAD_FOLIAGE_VERTEX_GLSL: Readonly<Record<string, string>> = {
  CUSTOM_VERTEX_DEFINITIONS: '#if defined(SRO_FOL_WIND) || defined(SRO_FOL_FLUTTER)\nvec3 sroWind(vec3 root) {\n  float t = wxB.w;\n  float z = clamp(wxB.z, 0.0, 1.0);\n  float ph = dot(root.xz, vec2(0.21, 0.17));\n  float sway = sin(t * 1.9 + ph) * 0.65 + sin(t * 3.3 + ph * 1.7) * 0.35;\n  float gust = sin(dot(root.xz, wxB.xy) * 0.35 - t * 2.1);\n  return vec3(sway + 0.5 * z * gust + 0.6 * z, 0.4 + 2.2 * z, clamp(wxA.z, 0.0, 1.0));\n}\n#endif\n',
  CUSTOM_VERTEX_UPDATE_WORLDPOS: '#if defined(SRO_FOL_WIND) || defined(SRO_FOL_FLUTTER)\n{\n  vec3 folRoot = finalWorld[3].xyz;\n  float folH = clamp(worldPos.y - folRoot.y, 0.0, 12.0);\n  float folZ = clamp(wxB.z, 0.0, 1.0);\n  vec3 folO = vec3(0.0);\n#ifdef SRO_FOL_WIND\n  vec3 folWd = sroWind(folRoot);\n  float folB = folZ * folH * folH * 0.012 * folWd.x;\n  folO = vec3(wxB.x * folB, 0.0, wxB.y * folB);\n#endif\n#ifdef SRO_FOL_FLUTTER\n  float folF = sin(wxB.w * 7.3 + dot(worldPos.xyz, vec3(1.7, 2.3, 1.1))) * (0.012 + 0.05 * folZ) * clamp(folH / 3.0, 0.0, 1.0);\n  folO += vec3(wxB.x * folF, 0.5 * folF, wxB.y * folF);\n#endif\n  worldPos.xyz += folO;\n  vPositionW = worldPos.xyz;\n}\n#endif\n',
}

export const HEAD_FOLIAGE_FRAGMENT_WGSL: Readonly<Record<string, string>> = {
  CUSTOM_FRAGMENT_DEFINITIONS: '#ifdef SRO_FOL_TRANSL\nvar<private> sroFolSh: f32 = -1.0;\n#endif\n',
  '!(diffuseBase\\+=info\\.diffuse\\*shadow;)': '$1\n#ifdef SRO_FOL_TRANSL\nif (sroFolSh < 0.0) {\n  sroFolSh = shadow;\n}\n#endif\n',
  CUSTOM_FRAGMENT_BEFORE_FINALCOLORCOMPOSITION: '#ifdef SRO_FOL_TRANSL\n#if defined(LIGHT0) && defined(DIRLIGHT0)\n{\n  let folL = normalize(-light0.vLightData.xyz);\n  let folBack = pow(clamp(dot(viewDirectionW, -folL), 0.0, 1.0), 4.0);\n  let folThick = 0.5 + 0.5 * clamp(surfaceAlbedo.g * 4.0, 0.0, 1.0);\n  let folSh = select(sroFolSh, 1.0, sroFolSh < 0.0);\n  finalDiffuse = finalDiffuse + light0.vLightDiffuse.rgb * surfaceAlbedo * (uniforms.sroFol.x * folBack * folThick * folSh * 0.31830989);\n}\n#endif\n#endif\n',
}

export const HEAD_FOLIAGE_FRAGMENT_GLSL: Readonly<Record<string, string>> = {
  CUSTOM_FRAGMENT_DEFINITIONS: '#ifdef SRO_FOL_TRANSL\nfloat sroFolSh = -1.0;\n#endif\n',
  '!(diffuseBase\\+=info\\.diffuse\\*shadow;)': '$1\n#ifdef SRO_FOL_TRANSL\nif (sroFolSh < 0.0) {\n  sroFolSh = shadow;\n}\n#endif\n',
  CUSTOM_FRAGMENT_BEFORE_FINALCOLORCOMPOSITION: '#ifdef SRO_FOL_TRANSL\n#if defined(LIGHT0) && defined(DIRLIGHT0)\n{\n  vec3 folL = normalize(-light0.vLightData.xyz);\n  float folBack = pow(clamp(dot(viewDirectionW, -folL), 0.0, 1.0), 4.0);\n  float folThick = 0.5 + 0.5 * clamp(surfaceAlbedo.g * 4.0, 0.0, 1.0);\n  float folSh = sroFolSh < 0.0 ? 1.0 : sroFolSh;\n  finalDiffuse += light0.vLightDiffuse.rgb * surfaceAlbedo * (sroFol.x * folBack * folThick * folSh * 0.31830989);\n}\n#endif\n#endif\n',
}
